[package]
name = "ongrok-relay-client"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow = "1.0.104"
bytes = "1.12.1"
clap = { version = "4.6.6", features = ["derive", "env"] }
directories = "6.0.0"
dotenvy = "0.15.7"
ed25519-dalek = { version = "3.0.0", default-features = false }
http-body-util = "0.1.5"
hyper = { version = "1.11.0", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
libongrok = { version = "0.1.0", path = "../libongrok" }
mimalloc = "0.1.52"
quinn = "0.11.11"
rand = "0.10.2"
rustls = { version = "0.23.43", default-features = false, features = ["std", "tls12", "ring"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["full"] }
tokio-rustls = { version = "0.26.4", default-features = false, features = ["ring", "tls12"] }
tokio-util = { version = "0.7.19", features = ["compat"] }
tracing = { version = "0.1.44", features = ["attributes"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
yamux = "0.14.0"
